### ISSUE TITLE
string number with prefixed plus gives error

### ISSUE THREAD

**Issue by aviaryan** [MikeMcl/decimal.js#32]
```
> decimal.add('+2')
Error: [DecimalError] Invalid argument: +2
    at Error (native)
    at parseOther (/home/aviaryan/dev/nodejs/BigEval.js/node_modules/decimal.js/decimal.js:3736:13)
    at new Decimal (/home/aviaryan/dev/nodejs/BigEval.js/node_modules/decimal.js/decimal.js:4432:55)
    at Decimal.P.plus.P.add (/home/aviaryan/dev/nodejs/BigEval.js/node_modules/decimal.js/decimal.js:1514:9)
    at repl:1:3
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
```

I remember this used to work earlier. Was it discontinued on purpose or Is it a bug.
I vote for handling such cases.

**Comment by MikeMcl** [comment]
It was discontinued as from *v5*

From the *CHANGELOG*

>> String values containing whitespace or a plus sign are no longer accepted.

I don't want it to be the responsibility of this library to handle such cases.
